### PR TITLE
[Synthetics] Fix api min location failed in test

### PR DESCRIPTION
**Pull request by romainberger**
# What does this PR do?

Fix min location failed value in synthetics tests.

- [x] This PR includes all [newly recorded cassettes](/DEVELOPMENT.md) for any modified tests.

### CODE REVIEW

**Review by therve — CHANGES_REQUESTED** [review]
You need to update cassettes for `TestSyntheticsMultipleTestsOperations` as well.

**Review by therve — CHANGES_REQUESTED** [review]
Sorry same for `TestSyntheticsUpdateTestErrors`

**Comment by romainberger** [comment]
Should be good now, I've updated all cassettes that needed to be.

**Review by therve — APPROVED** [review]

**Pull request merged**
