### PR TITLE
DRAFT // Add a new Synthetics Assertion Operator

### PR DESCRIPTION
**Pull request by chussenot**
This PR have the goal to allow the validadeJSONPath operator on synthetic probes.
https://github.com/terraform-providers/terraform-provider-datadog/issues/566

### CODE REVIEW

**Comment by chussenot** [comment]
How to add this in the client generation pipeline @anthony-palmeira?

**Comment by therve** [comment]
I think it's done in https://github.com/DataDog/datadog-api-spec/pull/451. Can you have a look and see if it works for you?

**Comment by chussenot** [comment]
@therve Are you sure that it's a public repo? :)

**Comment by therve** [comment]
Oh I'm sorry. Yes indeed it's not a public repository. We're handling that spec update, the client should be changed soon now.

**Comment by chussenot** [comment]
The last merge on the master branch may do the job.

**Pull request closed without merging**
